### PR TITLE
fix: validation for multiple google accounts

### LINKED ISSUE #137: [BUG] :bug: We should not be able to connect same google/gmail account
### Current Behaviour

If we connect same google account than it will create new object inside services array of user document in database

image

as you see there are 2 same emails as two different accounts

### Expected Behaviour

There should be a validation that same account can't be added again and user should be redirected to frontend
application

### Steps To Reproduce

1. signup with new account
2. connect a google account eg: `multiiemail@gmail.com`
3. again connect same google account which is `multiiemail@gmail.com`
4. now see that 2 accounts with same email are added to `connected_services` array in `user` document

### Anything else?

Add `if` condition validation [here](https://github.com/MultiEmail/backend/blob/main/src/controllers/auth.controller.ts#L559)

### PR DESCRIPTION
**Pull request by tharun634**
### Description

- Added validation to prevent connecting multiple Google accounts

### Checklist:

-   [x] This pull request follow our contribution guidelines
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation (postman and wiki)
-   [ ] I have written tests for the code
-   [ ] I have updated .env.example file for new .env variables

### What is current behavior?

Closes #137 

### What is new behavior?

- Checks if there is a connected google service, if there is, returns to Frontend with a `HTTP 409 Conflict`

### CODE REVIEW

File: src/controllers/auth.controller.ts [hunk 1]
```diff
@@ -556,7 +556,10 @@ export const googleOauthHandler = async (req: Request, res: Response) => {
 			return res.status(StatusCodes.NOT_FOUND).redirect(FRONTEND_URL);
 		}
 
-		// TODO: if account is already added than redirect to frontend
+		// if account is already added than redirect to frontend
+		if (foundUser.connected_services.filter((s) => s.service === "google").length) {
```
Comment (aayushchugh) [inline src/controllers/auth.controller.ts]: don't check with service check the email because we can connect multiple google accounts

**Review by aayushchugh — CHANGES_REQUESTED** [review]

**Review by aayushchugh — APPROVED** [review]
good
