### PR TITLE
fix: send error if invalid access token

### LINKED ISSUE #104: [SECURITY] :lock: Check if access token is expired
### Description

If `access_token` is expired than throw error 

### How can we solve this

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by aayushchugh**

### CODE REVIEW

File: src/middleware/deserializeUser.middleware.ts [hunk 1]
```diff
@@ -15,7 +16,11 @@ import { verifyJWT } from "../utils/jwt.util";
...
 	const accessToken = (req.headers.authorization || "").replace(/^Bearer\s/, "");
 
-	if (!accessToken) return next();
+	if (!accessToken) {
+		return res.status(StatusCodes.UNAUTHORIZED).json({
+			error: "User is not logged in",
+		});
+	}
 
 	const decoded = await verifyJWT<{ _id: string }>(accessToken, "ACCESS_TOKEN_PUBLIC_KEY");
```
Comment (is-it-ayush) [inline src/middleware/deserializeUser.middleware.ts:25]: Hey Ayush, Could you make this change and turn `ACCESS_TOKEN_PUBLIC_KEY` into a environemnt variable. Thank You!

**Review by is-it-ayush — APPROVED** [review]
All Looks Good! Thank You for the PR.

File: src/middleware/deserializeUser.middleware.ts (hunk 1 above)
Comment (aayushchugh) [reply src/middleware/deserializeUser.middleware.ts:25]: It's already in ENV
